# Generated by Django 5.2.2 on 2025-07-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
